"""Part 2: planet:house (9 planets x 12 houses = 108 entries)"""
import json, pathlib

DATA = []
SOURCE = "curated:jyotish:basic"

PLANET_HOUSE = {
    "sun": {
        1: ("Sun in 1st house — strong solar identity, health, leadership presence and physical vitality.", "Солнце в 1-м доме — сильная солярная идентичность, здоровье, лидерское присутствие, физическая витальность."),
        2: ("Sun in 2nd house — identity tied to family, wealth and speech; authority through resources.", "Солнце во 2-м доме — идентичность связана с семьёй, богатством и речью; авторитет через ресурсы."),
        3: ("Sun in 3rd house — strong will, courage and communication; authority in media, siblings, short travel.", "Солнце в 3-м доме — сильная воля, смелость и коммуникация; авторитет в СМИ, братьях и сёстрах, ближних путешествиях."),
        4: ("Sun in 4th house — authority linked to home, mother and private life; property and inner security.", "Солнце в 4-м доме — авторитет связан с домом, матерью и частной жизнью; собственность и внутренняя безопасность."),
        5: ("Sun in 5th house — strong creative intelligence, children, speculation and past-life merit.", "Солнце в 5-м доме — сильный творческий интеллект, дети, спекуляции и заслуги прошлых жизней."),
        6: ("Sun in 6th house — authority over enemies, health and service; competitive, resilient in conflict.", "Солнце в 6-м доме — авторитет над врагами, здоровьем и служением; конкурентоспособный, стойкий в конфликтах."),
        7: ("Sun in 7th house — strong partnerships and public dealings; can be demanding in marriage.", "Солнце в 7-м доме — сильные партнёрства и публичные дела; может быть требовательным в браке."),
        8: ("Sun in 8th house — transformation, hidden matters, longevity and occult; sudden changes to status.", "Солнце в 8-м доме — трансформация, скрытые дела, долголетие и оккульт; внезапные изменения статуса."),
        9: ("Sun in 9th house — dharma, father, spirituality and higher knowledge; strong moral authority.", "Солнце в 9-м доме — дхарма, отец, духовность и высшее знание; сильный нравственный авторитет."),
        10: ("Sun in 10th house — strong career, public reputation and worldly authority; natural leader.", "Солнце в 10-м доме — сильная карьера, публичная репутация и мирской авторитет; природный лидер."),
        11: ("Sun in 11th house — gains, elder siblings, social networks; recognition through groups.", "Солнце в 11-м доме — прибыли, старшие братья и сёстры, социальные сети; признание через группы."),
        12: ("Sun in 12th house — foreign lands, isolation, spirituality; vitality may be spent in hidden service.", "Солнце в 12-м доме — чужие земли, уединение, духовность; жизненные силы расходуются в скрытом служении."),
    },
    "moon": {
        1: ("Moon in 1st house — sensitive, receptive personality; fluctuating emotions, public appeal.", "Луна в 1-м доме — чувствительная, восприимчивая личность; колеблющиеся эмоции, общественное притяжение."),
        2: ("Moon in 2nd house — emotional attachment to family and wealth; fluctuating finances, nurturing speech.", "Луна во 2-м доме — эмоциональная привязанность к семье и богатству; колеблющиеся финансы, заботливая речь."),
        3: ("Moon in 3rd house — emotionally driven communication; creative writing, emotional courage.", "Луна в 3-м доме — эмоционально движимое общение; творческое письмо, эмоциональная смелость."),
        4: ("Moon in 4th house — strong connection to home, mother and inner peace; emotional foundation is key.", "Луна в 4-м доме — сильная связь с домом, матерью и душевным покоем; эмоциональная основа — ключевая."),
        5: ("Moon in 5th house — emotional creativity, deep love for children, intuitive intelligence.", "Луна в 5-м доме — эмоциональная творческость, глубокая любовь к детям, интуитивный интеллект."),
        6: ("Moon in 6th house — emotional sensitivity to health and service; fluctuating wellbeing.", "Луна в 6-м доме — эмоциональная чувствительность к здоровью и служению; колеблющееся самочувствие."),
        7: ("Moon in 7th house — emotional partnerships; marriage is emotionally central; public relatability.", "Луна в 7-м доме — эмоциональные партнёрства; брак эмоционально центральный; общественная близость."),
        8: ("Moon in 8th house — deep emotional transformation; interest in hidden matters, cycles of loss and renewal.", "Луна в 8-м доме — глубокая эмоциональная трансформация; интерес к скрытым делам, циклам потери и обновления."),
        9: ("Moon in 9th house — emotional connection to dharma and teacher; spiritual nourishment through travel.", "Луна в 9-м доме — эмоциональная связь с дхармой и учителем; духовное питание через путешествия."),
        10: ("Moon in 10th house — public career, fame and emotional involvement in profession.", "Луна в 10-м доме — публичная карьера, слава и эмоциональная вовлечённость в профессию."),
        11: ("Moon in 11th house — emotional fulfillment through gains and social networks; fluctuating income.", "Луна в 11-м доме — эмоциональное удовлетворение через прибыли и социальные сети; колеблющийся доход."),
        12: ("Moon in 12th house — deep inner life, spiritual sensitivity, isolation; sleep disturbances possible.", "Луна в 12-м доме — глубокая внутренняя жизнь, духовная чувствительность, уединение; возможны нарушения сна."),
    },
    "mars": {
        1: ("Mars in 1st house — energetic, assertive personality; strong physical drive, competitive nature.", "Марс в 1-м доме — энергичная, напористая личность; сильное физическое стремление, соревновательная натура."),
        2: ("Mars in 2nd house — sharp speech, aggressive pursuit of wealth; conflicts over family resources.", "Марс во 2-м доме — острая речь, агрессивное стремление к богатству; конфликты из-за семейных ресурсов."),
        3: ("Mars in 3rd house — courageous, competitive in communication; technical skill, strong siblings.", "Марс в 3-м доме — смелый, конкурентный в коммуникации; технический навык, сильные братья и сёстры."),
        4: ("Mars in 4th house — energy in home and property; possible domestic conflicts; real estate activity.", "Марс в 4-м доме — энергия в доме и собственности; возможные домашние конфликты; активность в недвижимости."),
        5: ("Mars in 5th house — passionate creativity and bold speculation; strong children, athletic intelligence.", "Марс в 5-м доме — страстная творческость и смелые спекуляции; сильные дети, спортивный интеллект."),
        6: ("Mars in 6th house — excellent for overcoming enemies and health challenges; strong service drive.", "Марс в 6-м доме — отличный для преодоления врагов и проблем со здоровьем; сильное стремление к служению."),
        7: ("Mars in 7th house — assertive or combative in partnerships; passionate but potentially conflictual marriage.", "Марс в 7-м доме — напористый или конфликтный в партнёрствах; страстный, но потенциально конфликтный брак."),
        8: ("Mars in 8th house — intense transformation, surgery, occult; sudden upheavals and hidden energy.", "Марс в 8-м доме — интенсивная трансформация, хирургия, оккульт; внезапные потрясения и скрытая энергия."),
        9: ("Mars in 9th house — active pursuit of dharma; strong father or teacher; religious zeal.", "Марс в 9-м доме — активное стремление к дхарме; сильный отец или учитель; религиозный пыл."),
        10: ("Mars in 10th house — strong career drive; leadership in technical or competitive fields.", "Марс в 10-м доме — сильное карьерное стремление; лидерство в технических или конкурентных областях."),
        11: ("Mars in 11th house — energetic pursuit of gains; competitive social networks; active ambitions.", "Марс в 11-м доме — энергичное стремление к прибылям; конкурентные социальные сети; активные амбиции."),
        12: ("Mars in 12th house — energy spent in foreign lands, spiritual effort or hidden battles.", "Марс в 12-м доме — энергия расходуется в чужих землях, духовных усилиях или скрытых битвах."),
    },
    "mercury": {
        1: ("Mercury in 1st house — intelligent, communicative personality; youthful, quick-thinking presence.", "Меркурий в 1-м доме — умная, коммуникабельная личность; юный, быстро думающий облик."),
        2: ("Mercury in 2nd house — skilled in speech and commerce; talent for languages and financial calculation.", "Меркурий во 2-м доме — умелый в речи и торговле; талант к языкам и финансовым расчётам."),
        3: ("Mercury in 3rd house — own house theme. Excellent communication, writing, media and short travel.", "Меркурий в 3-м доме — тема собственного дома. Отличная коммуникация, письмо, медиа и ближние путешествия."),
        4: ("Mercury in 4th house — intellectual home environment; interest in land, education and inner analysis.", "Меркурий в 4-м доме — интеллектуальная домашняя среда; интерес к земле, образованию и внутреннему анализу."),
        5: ("Mercury in 5th house — creative intelligence, children with sharp minds; speculative wit.", "Меркурий в 5-м доме — творческий интеллект, дети с острым умом; остроумные спекуляции."),
        6: ("Mercury in 6th house — analytical approach to health and service; debates, legal analysis.", "Меркурий в 6-м доме — аналитический подход к здоровью и служению; дебаты, юридический анализ."),
        7: ("Mercury in 7th house — intellectual partnerships; business through communication and negotiation.", "Меркурий в 7-м доме — интеллектуальные партнёрства; бизнес через коммуникацию и переговоры."),
        8: ("Mercury in 8th house — penetrating research, occult study, hidden knowledge and transformation.", "Меркурий в 8-м доме — проникающие исследования, оккультное изучение, скрытое знание и трансформация."),
        9: ("Mercury in 9th house — philosophical intellect, teaching, writing on dharma and higher knowledge.", "Меркурий в 9-м доме — философский интеллект, преподавание, написание о дхарме и высшем знании."),
        10: ("Mercury in 10th house — career in communication, media, writing or trade; public intellectual.", "Меркурий в 10-м доме — карьера в коммуникациях, медиа, письме или торговле; публичный интеллектуал."),
        11: ("Mercury in 11th house — gains through intellect and networks; socially connected and witty.", "Меркурий в 11-м доме — прибыли через интеллект и сети; социально связанный и остроумный."),
        12: ("Mercury in 12th house — introspective or meditative mind; writing in isolation; foreign languages.", "Меркурий в 12-м доме — интроспективный или медитативный ум; письмо в уединении; иностранные языки."),
    },
    "jupiter": {
        1: ("Jupiter in 1st house — wise, generous, fortunate personality; natural teacher and guide.", "Юпитер в 1-м доме — мудрая, щедрая, удачливая личность; природный учитель и наставник."),
        2: ("Jupiter in 2nd house — wealth, eloquence and family blessings; multiple income streams.", "Юпитер во 2-м доме — богатство, красноречие и семейные благословения; множество источников дохода."),
        3: ("Jupiter in 3rd house — wise communication; philosophical writing; generous toward siblings.", "Юпитер в 3-м доме — мудрое общение; философское письмо; щедрость по отношению к братьям и сёстрам."),
        4: ("Jupiter in 4th house — happiness at home, real estate blessings, devoted mother, inner peace.", "Юпитер в 4-м доме — счастье дома, благословения недвижимости, преданная мать, душевный покой."),
        5: ("Jupiter in 5th house — blessed creative intelligence, good children, spiritual merit, speculative luck.", "Юпитер в 5-м доме — благословенный творческий интеллект, хорошие дети, духовные заслуги, удача в спекуляциях."),
        6: ("Jupiter in 6th house — overcomes enemies through wisdom; service and health blessed but debt possible.", "Юпитер в 6-м доме — побеждает врагов мудростью; служение и здоровье благословлены, но возможны долги."),
        7: ("Jupiter in 7th house — wise, dharmic spouse; partnerships blessed; strong public relations.", "Юпитер в 7-м доме — мудрый, дхармичный супруг; партнёрства благословлены; сильные публичные отношения."),
        8: ("Jupiter in 8th house — wisdom through transformation and occult; longevity and inherited wealth.", "Юпитер в 8-м доме — мудрость через трансформацию и оккульт; долголетие и унаследованное богатство."),
        9: ("Jupiter in 9th house — own house theme. Exceptional dharma, learning, travel and spiritual blessings.", "Юпитер в 9-м доме — тема собственного дома. Исключительная дхарма, обучение, путешествия и духовные благословения."),
        10: ("Jupiter in 10th house — prestigious career, public wisdom, authority in law, teaching or administration.", "Юпитер в 10-м доме — престижная карьера, публичная мудрость, авторитет в законе, преподавании или управлении."),
        11: ("Jupiter in 11th house — abundant gains and fulfillment of desires; influential social networks.", "Юпитер в 11-м доме — обильные прибыли и исполнение желаний; влиятельные социальные сети."),
        12: ("Jupiter in 12th house — spiritual liberation, foreign spiritual connection, charitable giving.", "Юпитер в 12-м доме — духовное освобождение, иностранная духовная связь, благотворительность."),
    },
    "venus": {
        1: ("Venus in 1st house — charming, attractive, pleasure-loving personality; refined aesthetics.", "Венера в 1-м доме — обаятельная, привлекательная, любящая удовольствия личность; утончённая эстетика."),
        2: ("Venus in 2nd house — wealth through beauty and art; pleasant speech, family happiness.", "Венера во 2-м доме — богатство через красоту и искусство; приятная речь, семейное счастье."),
        3: ("Venus in 3rd house — artistic communication; beauty in writing and media; harmonious siblings.", "Венера в 3-м доме — художественная коммуникация; красота в письме и медиа; гармоничные братья и сёстры."),
        4: ("Venus in 4th house — beautiful, comfortable home; happiness from mother; love of property.", "Венера в 4-м доме — красивый, комфортный дом; счастье от матери; любовь к собственности."),
        5: ("Venus in 5th house — creative arts, romantic intelligence, beautiful children, speculation in luxury.", "Венера в 5-м доме — творческие искусства, романтический интеллект, красивые дети, спекуляции в роскоши."),
        6: ("Venus in 6th house — service through beauty; health in aesthetics; relationships may involve imbalance.", "Венера в 6-м доме — служение через красоту; здоровье в эстетике; отношения могут быть неравновесными."),
        7: ("Venus in 7th house — own house theme. Loving, harmonious partnerships; blessed marriage and business.", "Венера в 7-м доме — тема собственного дома. Любящие, гармоничные партнёрства; благословенный брак и бизнес."),
        8: ("Venus in 8th house — sensual depth and transformation in love; inheritance through partnership.", "Венера в 8-м доме — чувственная глубина и трансформация в любви; наследство через партнёрство."),
        9: ("Venus in 9th house — love of travel, philosophy and spiritual beauty; devoted to teacher.", "Венера в 9-м доме — любовь к путешествиям, философии и духовной красоте; преданность учителю."),
        10: ("Venus in 10th house — career in arts, beauty or diplomacy; public charm and graceful authority.", "Венера в 10-м доме — карьера в искусстве, красоте или дипломатии; публичное обаяние и изящный авторитет."),
        11: ("Venus in 11th house — gains through beauty and social connections; artistic networks flourish.", "Венера в 11-м доме — прибыли через красоту и социальные связи; художественные сети процветают."),
        12: ("Venus in 12th house — spiritual love, foreign pleasures, bedroom arts; hidden romantic life.", "Венера в 12-м доме — духовная любовь, иностранные удовольствия, искусства спальни; скрытая романтическая жизнь."),
    },
    "saturn": {
        1: ("Saturn in 1st house — serious, disciplined, slow-developing personality; physical endurance over time.", "Сатурн в 1-м доме — серьёзная, дисциплинированная, медленно развивающаяся личность; физическая выносливость со временем."),
        2: ("Saturn in 2nd house — delayed or restricted wealth; disciplined speech; family duties are heavy.", "Сатурн во 2-м доме — задержанное или ограниченное богатство; дисциплинированная речь; семейные обязанности тяжелы."),
        3: ("Saturn in 3rd house — structured communication; serious sibling relationships; disciplined effort in skills.", "Сатурн в 3-м доме — структурированное общение; серьёзные отношения с братьями и сёстрами; дисциплинированные усилия в навыках."),
        4: ("Saturn in 4th house — restrictions around home and mother; karmic duties in domestic life.", "Сатурн в 4-м доме — ограничения вокруг дома и матери; кармические обязанности в домашней жизни."),
        5: ("Saturn in 5th house — delayed children or creative expression; disciplined intellect; austere pleasures.", "Сатурн в 5-м доме — задержанные дети или творческое выражение; дисциплинированный интеллект; строгие удовольствия."),
        6: ("Saturn in 6th house — own house theme. Exceptional persistence in overcoming enemies, disease and debt.", "Сатурн в 6-м доме — тема собственного дома. Исключительная настойчивость в преодолении врагов, болезней и долгов."),
        7: ("Saturn in 7th house — serious, karmic or delayed partnerships; disciplined in marriage and business.", "Сатурн в 7-м доме — серьёзные, кармические или задержанные партнёрства; дисциплинированный в браке и бизнесе."),
        8: ("Saturn in 8th house — longevity through discipline; karmic transformation; interest in enduring hidden matters.", "Сатурн в 8-м доме — долголетие через дисциплину; кармическая трансформация; интерес к устойчивым скрытым делам."),
        9: ("Saturn in 9th house — disciplined dharma; serious philosophical outlook; karmic teacher relationship.", "Сатурн в 9-м доме — дисциплинированная дхарма; серьёзный философский взгляд; кармические отношения с учителем."),
        10: ("Saturn in 10th house — own house theme. Disciplined, slow-built but lasting career authority.", "Сатурн в 10-м доме — тема собственного дома. Дисциплинированный, медленно построенный, но прочный карьерный авторитет."),
        11: ("Saturn in 11th house — gains through sustained effort; disciplined social networks; delayed fulfillment.", "Сатурн в 11-м доме — прибыли через устойчивые усилия; дисциплинированные социальные сети; отложенное исполнение."),
        12: ("Saturn in 12th house — own house theme. Spiritual austerity, foreign isolation, karmic liberation.", "Сатурн в 12-м доме — тема собственного дома. Духовный аскетизм, иностранное уединение, кармическое освобождение."),
    },
    "rahu": {
        1: ("Rahu in 1st house — unusual, magnetic personality; unconventional path of self-expression.", "Раху в 1-м доме — необычная, магнетическая личность; нестандартный путь самовыражения."),
        2: ("Rahu in 2nd house — unusual accumulation of wealth; foreign speech patterns; irregular family.", "Раху во 2-м доме — необычное накопление богатства; иностранные речевые паттерны; нестандартная семья."),
        3: ("Rahu in 3rd house — obsessive communication; unconventional media work; foreign or digital focus.", "Раху в 3-м доме — навязчивое общение; нестандартная медиаработа; иностранный или цифровой фокус."),
        4: ("Rahu in 4th house — unusual domestic life; foreign homeland; unconventional mother relationship.", "Раху в 4-м доме — необычная домашняя жизнь; иностранная родина; нестандартные отношения с матерью."),
        5: ("Rahu in 5th house — unconventional creative intelligence; unusual children; speculative obsession.", "Раху в 5-м доме — нестандартный творческий интеллект; необычные дети; спекулятивная одержимость."),
        6: ("Rahu in 6th house — powerful for overcoming enemies through unconventional means; unusual health issues.", "Раху в 6-м доме — мощный для преодоления врагов нестандартными средствами; необычные проблемы со здоровьем."),
        7: ("Rahu in 7th house — foreign or unusual partner; unconventional business alliances.", "Раху в 7-м доме — иностранный или необычный партнёр; нестандартные деловые союзы."),
        8: ("Rahu in 8th house — intense fascination with hidden, occult and transformative realms.", "Раху в 8-м доме — сильное влечение к скрытым, оккультным и трансформирующим сферам."),
        9: ("Rahu in 9th house — foreign philosophy, unconventional dharma; obsessive spiritual seeking.", "Раху в 9-м доме — иностранная философия, нестандартная дхарма; навязчивый духовный поиск."),
        10: ("Rahu in 10th house — rise through unconventional means; foreign or technology-related career.", "Раху в 10-м доме — подъём нестандартными средствами; иностранная или связанная с технологиями карьера."),
        11: ("Rahu in 11th house — unusual gains; foreign or digital networks; obsessive fulfillment of desires.", "Раху в 11-м доме — необычные прибыли; иностранные или цифровые сети; навязчивое исполнение желаний."),
        12: ("Rahu in 12th house — foreign lands and spiritual obsession; hidden vices or spiritual breakthroughs.", "Раху в 12-м доме — иностранные земли и духовная одержимость; скрытые пороки или духовные прорывы."),
    },
    "ketu": {
        1: ("Ketu in 1st house — spiritual, detached personality; past-life identity released; sharp perception.", "Кету в 1-м доме — духовная, отстранённая личность; отпускание идентичности прошлых жизней; острое восприятие."),
        2: ("Ketu in 2nd house — detachment from family wealth and speech; past-life resources internalized.", "Кету во 2-м доме — отстранённость от семейного богатства и речи; ресурсы прошлых жизней усвоены."),
        3: ("Ketu in 3rd house — detachment from communication efforts; latent skill; spiritual courage.", "Кету в 3-м доме — отстранённость от коммуникационных усилий; скрытый навык; духовное мужество."),
        4: ("Ketu in 4th house — detachment from home and motherland; karmic release of domestic security.", "Кету в 4-м доме — отстранённость от дома и родины; кармическое освобождение от домашней безопасности."),
        5: ("Ketu in 5th house — detachment from children and creative ego; past-life spiritual practice returns.", "Кету в 5-м доме — отстранённость от детей и творческого эго; возвращение духовной практики прошлых жизней."),
        6: ("Ketu in 6th house — karmic dissolution of enemies; past-life service mastery; spiritual healing.", "Кету в 6-м доме — кармическое растворение врагов; мастерство служения из прошлых жизней; духовное исцеление."),
        7: ("Ketu in 7th house — detachment from partnerships; spiritual companion or solitude preferred.", "Кету в 7-м доме — отстранённость от партнёрств; предпочтение духовного спутника или одиночества."),
        8: ("Ketu in 8th house — deep occult perception; past-life transformation mastery; sudden liberation.", "Кету в 8-м доме — глубокое оккультное восприятие; мастерство трансформации из прошлых жизней; внезапное освобождение."),
        9: ("Ketu in 9th house — detachment from formal dharma; liberation through direct experience of truth.", "Кету в 9-м доме — отстранённость от формальной дхармы; освобождение через прямой опыт истины."),
        10: ("Ketu in 10th house — detachment from career status; hidden mastery; unusual public recognition.", "Кету в 10-м доме — отстранённость от карьерного статуса; скрытое мастерство; необычное общественное признание."),
        11: ("Ketu in 11th house — detachment from social gains; past-life network released; solitary fulfillment.", "Кету в 11-м доме — отстранённость от социальных прибылей; сеть прошлых жизней отпущена; одинокое исполнение."),
        12: ("Ketu in 12th house — spiritual liberation; moksha indicator; deep meditation and renunciation.", "Кету в 12-м доме — духовное освобождение; индикатор мокши; глубокая медитация и отречение."),
    },
}

for planet, houses in PLANET_HOUSE.items():
    for house, (en, ru) in houses.items():
        DATA.append({
            "key": f"planet:{planet}:house:{house}",
            "source_id": SOURCE,
            "text_en": en,
            "text_ru": ru,
        })

out = pathlib.Path(__file__).parent / "part2_planet_house.jsonl"
with open(out, "w", encoding="utf-8") as f:
    for entry in DATA:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
print(f"Written {len(DATA)} entries to {out}")
